PLANET-5843 Replace some colors to align with the design system
greenpeace/planet4-styleguide pull request #97
Opened 2021-02-12 14:00 UTC by mleray

### Description
See https://jira.greenpeace.org/browse/PLANET-5843

**Black / Grey colors:**
- ~~#000000 = $black -> replace by #020202 = $grey-80~~
- ~~#030403 = $header-footer-bg -> replace by #020202 = $grey-80~~
- ~~#1a1a1a = none -> replace by #020202 = $grey-80~~
- ~~#052a30 = $dark-tiber -> replace by #020202 = $grey-80~~
- ~~#242424 = none -> replace by #23292d = $grey~~
- #a7a7a7 = $step-number -> unused, was removed with https://jira.greenpeace.org/browse/PLANET-5842
- #aaaaaa = none -> replace by #a3a5a7 = $grey-20 -> couldn't find it, seems unused

**Blue colors:**
- ~~#0a3351 = $med-blue -> replace by #074365 = $dark-blue~~
- ~~#094464 = $cookie-blue -> replace by #074365 = $dark-blue~~
- ~~#014c8c = $menu-blue ->replace by #020202 = $grey-80~~
- ~~#0058cc = $link-hover-color -> replace by #006dfd = $link-color~~
- ~~#3290de = $blue-80 -> replace by #006dfd = $link-color~~
- ~~#21cbca = $java-dark -> replace by #68dfde = $aquamarine~~
- ~~#093944 = $blue-tiber -> replace by #074365 = $dark-blue~~
- #c0dbe2 = $cookie-bkg -> replace by #FFFFFF = $white -> we leave this one for now because it looks weird in white, the component will be redesigned
- ~~#074365 = none -> replace by #074365 = $dark-blue~~
- ~~#86eee7 = $spray = -> replace by #FFFFFF = $white~~
- ~~#3b5998 = $facebook = -> replace by #4267b2~~

**Green colors:**
- ~~#418482 = $faded-jade -> replace by #074365 = $dark-blue~~
- ~~#0f6459 = $eden -> replace by #FFFFFF = $white~~
- ~~#1e5f65 = $top-nav -> replace by #006dfd = $link-color~~
- ~~#d9e6d7 = $green-20 -> replace by #FFFFFF = $white~~

**Orange / Red colors:**
- ~~#ad2330 = $red -> replace by #F75848~~
- ~~#a01604 = $red -> replace by #F75848~~
- ~~#dd4a22 = $orange-active -> replace by #ee562d = $orange-hover~~
- ~~#ff3333 = none -> replace by #F75848~~
- ~~#faf7ec = $brown-bg -> replace by #FFFFFF = $white~~
- ~~#ea7179 = $email -> replace by #8a49de~~

### Related PRs
- master-theme:
- plugin-gutenberg-blocks:

2021-02-15 12:09 UTC, sagarsdeshmukh approved these changes
👍

2021-02-16 14:55 UTC, Inwerpsel requested changes

2021-02-16 14:55 UTC, Inwerpsel commented on src/base/_typography.scss
> +    color: var(--link--color, $link-color);
If the variable already existed we need to be careful when removing it, since it might be used. But in this case it makes more sense to keep it and only change the default value, since this is very likely something people will want to customize.

2021-02-16 15:32 UTC, mleray commented on src/base/_typography.scss
> +    color: var(--link--color, $link-color);
Good point! Updated 🙂

2021-02-19 12:11 UTC, Inwerpsel commented on src/base/_colors.scss
> +$dark-orange: #f75848;
Is this addition intended? There's no usages of it.

2021-02-19 12:13 UTC, mleray commented on src/base/_colors.scss
> +$facebook: #4267b2;
Yep, it's the [right blue](https://usbrandcolors.com/facebook-colors/#:~:text=The%20official%20Facebook%20colors%20are%20blue%2C%20grey%2C%20black%20and%20white.) 🙂

2021-02-19 12:14 UTC, Inwerpsel commented on src/base/_colors.scss
> +$facebook: #4267b2;
Nice, so I guess the previous one is wrong :grimacing:

2021-02-19 12:18 UTC, Inwerpsel commented on src/components/_buttons.scss
> -    background-color: var(--btn-donate-background-color, $aquamarine);
Yeah I don't think we have disabled donate buttons anywhere :smile:

2021-02-19 12:18 UTC, mleray commented on src/base/_colors.scss
> +$dark-orange: #f75848;
[There is](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/498/files#diff-3238465c49f71c5a925559d938c7043c20b00964c7fa2022aebff259909d0825R105) 🙂

2021-02-19 13:41 UTC, Inwerpsel approved these changes
Looks good :+1:

2021-03-02 11:00 UTC, merged